# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image-pull.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image-pull.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10image-pull.proto\"\x1a\n\tImageName\x12\r\n\x05Image\x18\x01 \x01(\t\"1\n\x07Results\x12\r\n\x05stats\x18\x02 \x01(\x08\x12\x17\n\x0fImageMirrorName\x18\x03 \x01(\t2\\\n\tImagePull\x12*\n\x10\x43heckImageExists\x12\n.ImageName\x1a\x08.Results\"\x00\x12#\n\tPullImage\x12\n.ImageName\x1a\x08.Results\"\x00\x62\x06proto3')
)




_IMAGENAME = _descriptor.Descriptor(
  name='ImageName',
  full_name='ImageName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Image', full_name='ImageName.Image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=46,
)


_RESULTS = _descriptor.Descriptor(
  name='Results',
  full_name='Results',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='Results.stats', index=0,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ImageMirrorName', full_name='Results.ImageMirrorName', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['ImageName'] = _IMAGENAME
DESCRIPTOR.message_types_by_name['Results'] = _RESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageName = _reflection.GeneratedProtocolMessageType('ImageName', (_message.Message,), dict(
  DESCRIPTOR = _IMAGENAME,
  __module__ = 'image_pull_pb2'
  # @@protoc_insertion_point(class_scope:ImageName)
  ))
_sym_db.RegisterMessage(ImageName)

Results = _reflection.GeneratedProtocolMessageType('Results', (_message.Message,), dict(
  DESCRIPTOR = _RESULTS,
  __module__ = 'image_pull_pb2'
  # @@protoc_insertion_point(class_scope:Results)
  ))
_sym_db.RegisterMessage(Results)



_IMAGEPULL = _descriptor.ServiceDescriptor(
  name='ImagePull',
  full_name='ImagePull',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=99,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='CheckImageExists',
    full_name='ImagePull.CheckImageExists',
    index=0,
    containing_service=None,
    input_type=_IMAGENAME,
    output_type=_RESULTS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PullImage',
    full_name='ImagePull.PullImage',
    index=1,
    containing_service=None,
    input_type=_IMAGENAME,
    output_type=_RESULTS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEPULL)

DESCRIPTOR.services_by_name['ImagePull'] = _IMAGEPULL

# @@protoc_insertion_point(module_scope)
