name: Github Action CI
on: 
  push:
  schedule:
  - cron:  '30 21 * * *'

jobs:
  build:
    name: Build DockerImage ENV
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check Docker 
      env:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
      run: |
        uname -a
        sudo apt-get remove docker docker-engine docker.io containerd runc -y
        sudo apt update -y
        sudo apt-get install \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg-agent \
          software-properties-common -y
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
        sudo apt-get update -y
        sudo apt-get install docker-ce docker-ce-cli containerd.io -y
        docker version
        echo $password | sudo docker login "registry.cn-hangzhou.aliyuncs.com" -u "$username" --password-stdin 
    - name: Build Kubeadm ENV
      run: |
        sudo apt-get update && sudo apt-get install -y apt-transport-https curl
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list
        sudo apt-get clean
        sudo apt-get update 
        sudo apt-get install dpkg
        sudo apt-get install -y kubelet kubeadm kubectl
        sudo apt-mark hold kubelet kubeadm kubectl
    - name: Test Build
      run: |
        make local